version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: khmaker/foodgram:latest
    container_name: web
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static:/app/web/static
      - media:/app/web/media

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    volumes:
    - static:/app/web/static
    - media:/app/web/media
    - ./nginx:/etc/nginx/conf.d
    ports:
    - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
